#!/bin/bash
# run_once_5_aitools_1llama_cpp.sh
#
# Build llama.cpp from source for the accelerators this box actually has:
#
#   * NVIDIA GPU  -> CUDA build -> ~/projs/llama.cpp/build_cuda   (built here)
#   * Intel GPU   -> SYCL build -> ~/projs/llama.cpp/build_sycl   (built lazily)
#
# Each backend is its own CMake tree (one tree cannot hold two toolchains).
# The CUDA build runs during `cz apply`. The SYCL build + the ~1.5 GB oneAPI
# install are deferred: they are generated into a shared helper
# (~/.local/share/llama-cpp/lib.sh) and only executed when you first run
# `llama-server-sycl`, so a plain apply never pulls oneAPI.
#
# Per-backend launcher commands are written to ~/.local/bin:
#   llama-server-cuda   # -> build_cuda   (CUDA_VISIBLE_DEVICES)
#   llama-server-sycl   # -> build_sycl   (auto device select, overridable via env)
#
# Root is only ever used for commands allowed by the scoped NOPASSWD sudoers
# drop-in (see AGENTS.md): apt, usermod, curl, mkdir, chmod, cp, mv, tee.
# The oneAPI installer runs as the *user* because bash/sh is NOT in that alias,
# so no sudo is required for it.

set -o pipefail
export DEBIAN_FRONTEND=noninteractive

# --- paths ------------------------------------------------------------------
LLAMA_DIR="$HOME/projs/llama.cpp"
BUILD_CUDA="$LLAMA_DIR/build_cuda"
NCPUS="$(grep -c '^processor' /proc/cpuinfo 2>/dev/null || echo 4)"
LIB_DIR="$HOME/.local/share/llama-cpp"
LIB="$LIB_DIR/lib.sh"

log() { echo "$(basename "$0"): $*"; }

# --- GPU presence (lspci needs no driver loaded, so never false-negative) -----
# Rule: only the LAST grep in a pipeline may use -q. An intermediate -q exits
# after its first match and emits only that one line, so a later grep can miss
# the real device (this bit us: the DG1 VGA line came after an earlier match
# and got dropped). has_nvidia and has_intel are independent checks.
has_nvidia()  { lspci 2>/dev/null | grep -qiE 'nvidia'; }
has_intel_gpu() {
    # decoupled: the display-class prefilter must pass ALL matching lines (no
    # -q); only the final vendor grep uses -q.
    lspci 2>/dev/null | grep -iE 'vga|3d|display' | grep -qi 'intel corporation'
}

grant_render_video_groups() {
    sudo usermod -aG render "$USER"
    sudo usermod -aG video "$USER"
    log "added $USER to render + video groups (log out/in for it to take effect)."
}

# --- builders ---------------------------------------------------------------
# NOTE: the source dir is passed EXPLICITLY to cmake (-B build $LLAMA_DIR) so a
# stale/pwd-independent CMakeLists lookup never points at the wrong folder.
build_cuda() {
    local ref="$1"
    fetch_llama_cpp "$ref"
    log "Installing CUDA build dependencies..."
    sudo apt install -y glslang-dev glslc spirv-headers libssl-dev libnccl-dev ccache nvidia-cuda-toolkit
    log "Building llama.cpp (CUDA) -> $BUILD_CUDA"
    cmake -B "$BUILD_CUDA" "$LLAMA_DIR" -DGGML_CCACHE="${CACHE:-ON}" -DGGML_CUDA=ON \
        -DLLAMA_BUILD_TESTS=OFF -DLLAMA_BUILD_EXAMPLES=OFF -DLLAMA_BUILD_UI=OFF \
        -DLLAMA_BUILD_SERVER=ON
    cmake --build "$BUILD_CUDA" --config Release -j "$NCPUS"
}

# clone/fetch/checkout llama.cpp (idempotent; reuses an existing checkout)
fetch_llama_cpp() {
    local tag="$1"
    if [ ! -d "$LLAMA_DIR/.git" ]; then
        rm -rf "$LLAMA_DIR"
        git clone https://github.com/ggml-org/llama.cpp "$LLAMA_DIR"
    fi
    if ! ( cd "$LLAMA_DIR" && git fetch --all --prune && git checkout "$ref" ); then
        log "ERROR: could not fetch/checkout '$ref' in $LLAMA_DIR"
        return 1
    fi
}

# --- generated shared lib + launchers ---------------------------------------
write_generated_files() {
    mkdir -p "$LIB_DIR" "$HOME/.local/bin"

    # Shared helper for the SYCL backend: lazy oneAPI install + SYCL build.
    # Quoted heredoc -> written verbatim; vars resolve when a wrapper sources it.
    cat > "$LIB" <<'LLIB'
#!/bin/bash
# ~/.local/share/llama-cpp/lib.sh  (generated by run_once_5_aitools_1llama_cpp.sh)
# Helpers for the SYCL backend, sourced by ~/.local/bin/llama-server-sycl.
# oneAPI + the SYCL build are LAZY: only pulled in when the wrapper first runs.

set -o pipefail

LLAMA_DIR="${LLAMA_DIR:-$HOME/projs/llama.cpp}"
BUILD_SYCL="${BUILD_SYCL:-$LLAMA_DIR/build_sycl}"
NCPUS="$(grep -c '^processor' /proc/cpuinfo 2>/dev/null || echo 4)"

ONEAPI_HOME="${ONEAPI_HOME:-$HOME/.local/intel/oneapi}"
ONEAPI_INSTALLER_URL="${ONEAPI_INSTALLER_URL:-https://registrationcenter-download.intel.com/akdlm/IRC_NAS/8170208e-86db-4faa-a0d6-1ecf62699574/intel-deep-learning-essentials-2026.0.0.624_offline.sh}"
ONEAPI_SETVARS="$ONEAPI_HOME/setvars.sh"

log() { echo "llama-server-sycl: $*"; }

# clone/fetch/checkout llama.cpp (idempotent; reuses an existing checkout)
fetch_llama_cpp() {
    local ref="$1"
    if [ ! -d "$LLAMA_DIR/.git" ]; then
        rm -rf "$LLAMA_DIR"
        git clone https://github.com/ggml-org/llama.cpp "$LLAMA_DIR"
    fi
    if ! ( cd "$LLAMA_DIR" && git fetch --all --prune && git checkout "$ref" ); then
        log "ERROR: could not fetch/checkout '$ref' in $LLAMA_DIR"
        return 1
    fi
}

# lazy oneAPI install (user-local, idempotent; skips when icx is present)
ensure_oneapi() {
    if [ -x "$ONEAPI_HOME/compiler/latest/bin/icx" ] || command -v icx >/dev/null 2>&1; then
        log "oneAPI already present at $ONEAPI_HOME — skipping install."
        return 0
    fi
    local installer="$HOME/.local/share/oneapi/configure_oneapi.sh"
    mkdir -p "$(dirname "$installer")"
    log "Installing Intel Deep Learning Essentials (static installer, ~1.5 GB)..."
    if ! curl -fsSL "$ONEAPI_INSTALLER_URL" -o "$installer"; then
        log "ERROR: failed to download oneAPI installer from $ONEAPI_INSTALLER_URL"
        return 1
    fi
    chmod +x "$installer"
    # `-a` forwards the following args to the underlying installer; Intel's
    # documented non-interactive form: -a --silent --eula accept ...
    if ! bash "$installer" -a --silent --eula accept --install-dir "$ONEAPI_HOME"; then
        log "ERROR: oneAPI installer exited non-zero."
        return 1
    fi
    log "oneAPI installed to $ONEAPI_HOME."
}

# build the SYCL tree (needs oneAPI + a llama.cpp checkout)
build_sycl() {
    local tag="$1"
    ensure_oneapi || return 1
    fetch_llama_cpp "$tag"
    log "Building llama.cpp (SYCL) -> $BUILD_SYCL"
    # shellcheck disable=SC1091
    . "$ONEAPI_SETVARS"
    cmake -B "$BUILD_SYCL" "$LLAMA_DIR" -DGGML_CCACHE="${CACHE:-ON}" -DGGML_SYCL=ON \
        -DGGML_SYCL_F16=ON \
        -DCMAKE_C_COMPILER=icx -DCMAKE_CXX_COMPILER=icpx \
        -DLLAMA_BUILD_TESTS=OFF -DLLAMA_BUILD_EXAMPLES=OFF -DLLAMA_BUILD_UI=OFF \
        -DLLAMA_BUILD_SERVER=ON
    cmake --build "$BUILD_SYCL" --config Release -j "$NCPUS"
}

# 0 when oneAPI + the SYCL binary are both ready to run
llama_sycl_ready() {
    [ -x "$BUILD_SYCL/bin/llama" ] && [ -x "$ONEAPI_HOME/compiler/latest/bin/icx" ]
}
LLIB

    # CUDA launcher: point at the pre-built CUDA tree. Uses the dedicated
    # 'llama-server' binary (not the unified 'llama') so --cache-list works.
    cat > "$HOME/.local/bin/llama-server-cuda" <<'EOF_CUDA'
#!/bin/bash
# llama.cpp on the NVIDIA GPU (CUDA build). Passthrough: append serve/--cache-list
# etc, e.g.  llama-server-cuda --cache-list  or  llama-server-cuda serve -m ...
export CUDA_VISIBLE_DEVICES="${CUDA_VISIBLE_DEVICES:-0}"
LLAMA="$HOME/projs/llama.cpp/build_cuda/bin/llama-server"
if [ ! -x "$LLAMA" ]; then
    echo "llama-server-cuda: CUDA build not available at $LLAMA — run the build once." >&2
    exit 1
fi
# dedicated server binary: it (not the unified 'llama') exposes --cache-list
exec "$LLAMA" "$@"
EOF_CUDA

    # SYCL launcher: lazy-bootstrap oneAPI + SYCL build on first use, then run.
    cat > "$HOME/.local/bin/llama-server-sycl" <<'EOF_SYCL'
#!/bin/bash
# llama.cpp on the Intel GPU (SYCL / Level-Zero build).
# LAZY: bootstraps the oneAPI install + SYCL build on first use, then runs.
set -o pipefail
LIB="$HOME/.local/share/llama-cpp/lib.sh"
[ -f "$LIB" ] && . "$LIB"

# render/video access for the Intel device (non-interactive; harmless if it fails)
sudo -n usermod -aG render "$USER" 2>/dev/null || true
sudo -n usermod -aG video "$USER" 2>/dev/null || true

if ! llama_sycl_ready; then
    build_sycl origin/master || log "SYCL build failed — fix the above and re-run."
else
    log "SYCL build already up to date; running."
fi

# source oneAPI so the runtime libs are on LD_LIBRARY_PATH
if [ -f "$ONEAPI_SETVARS" ]; then
    export SETVARS_QUIET=1
    # shellcheck disable=SC1091
    . "$ONEAPI_SETVARS"
fi
# Auto-select the Intel GPU (DG1 is not exposed as a Level-Zero device here, so
# do NOT force level_zero:N). Override explicitly via env if needed.
if [ -n "${ONEAPI_DEVICE_SELECTOR:-}" ]; then export ONEAPI_DEVICE_SELECTOR; else unset ONEAPI_DEVICE_SELECTOR; fi

if [ ! -x "$BUILD_SYCL/bin/llama-server" ]; then
    log "SYCL build not available at $BUILD_SYCL/bin/llama-server — run this once to build it."
    exit 1
fi
# dedicated server binary: it (not the unified 'llama') exposes --cache-list
exec "$BUILD_SYCL/bin/llama-server" "$@"
EOF_SYCL

    chmod +x "$HOME/.local/bin/llama-server-cuda" "$HOME/.local/bin/llama-server-sycl"
    chmod +x "$LIB"
    log "wrote ~/.local/bin/llama-server-cuda, ~/.local/bin/llama-server-sycl and $LIB"
}

# --- main -------------------------------------------------------------------
if ! has_nvidia && ! has_intel_gpu; then
    log "No CUDA or SYCL-capable GPU detected — nothing to build."
    exit 0
fi

grant_render_video_groups

# Build from origin/master (unpinned) rather than a release tag: the --cache-list
# (HF cache) flag the wrappers rely on landed only in master (PR #20775); the
# latest release tag (b11064) predates it.
LLAMA_REF="origin/master"
log "Building $LLAMA_REF"

# --- CUDA (built here, during apply) ----------------------------------------
if has_nvidia; then
    build_cuda "$LATEST_RELEASE" || log "CUDA build failed — investigate above and re-run."
fi

# --- generate SYCL helper + launchers (lazy; SYCL itself builds on demand) ---
write_generated_files

log "Done. Backend-specific commands:"
log "  llama-server-cuda   # NVIDIA / CUDA  (build_cuda)"
log "  llama-server-sycl   # Intel  / SYCL  (build_sycl, built lazily on first run)"
# NOTE: the boot service (restart-llama-server) is CUDA-only by design; the
# SYCL server is started with the llama-server-sycl command above.
#
# CUDA init error on suspend/resume (fixed upstream):
# https://github.com/ggml-org/llama.cpp/issues/7218
