# https://pi.dev/docs/latest/tmux
set -g mouse on
set -g extended-keys on
## on version >3.5 : set -g extended-keys-format csi-u


# Source - https://stackoverflow.com/a/23187030
# Posted by pymkin, modified by community. See post 'Timeline' for change history
# Retrieved 2026-07-29, License - CC BY-SA 4.0

# fix ssh agent when tmux is detached
setenv -g SSH_AUTH_SOCK $HOME/.ssh/ssh_auth_sock
