version = 1

[*]
ctx-size = 0
batch-size = -1
fit = on
jinja = on
kv-unified = off
cache-type-k = q4_0
cache-type-v = q4_0
flash-attn = on
cache-ram = 0

#[deepreinforce-ai/Ornith-1.5-9B-GGUF]
#temperature = 0.6
#top-p = 0.95
#top-k = 20
#min-p = 0.05
#rope-scaling = yarn
#rope-scale = 4

[deepreinforce-ai/Ornith-1.0-9B-GGUF]
temperature = 0.6
top-p = 0.95
top-k = 20
min-p = 0.05

[google/gemma-4-E4B-it-qat-q4_0-gguf:IT]
kv-offload = yes
temperature = 1.0
top-p = 0.95
top-k = 64

[Qwen/Qwen3-4B-GGUF:Q4_K_M]
rope-scaling = yarn
rope-scale = 4
yarn-orig-ctx = 64000
reasoning = on
temperature = 0.6
top-p = 0.95
top-k = 20
min-p = 0
presence-penalty = 1.5

[prism-ml/Bonsai-8B-gguf:Q1]
temperature =  0.5
top-p = 0.85
top-k = 20

[zai-org/glm-edge-v-5b-gguf:Q4_K_M]
# no classic jinja as message format, without jinja issue with tools params

[tiiuae/Falcon-H1-3B-Instruct-GGUF:Q4_K_M]
# won't call tools at all

[Abiray/Nanbeige4.2-3B-GGUF:Q4_K_M]
# PR on llama-cpp pending

[NexaAI/Octopus-v2-gguf-awq:Q4_K_M]
# jinja exception on template parser

[InternScience/Agents-A1-4B-Q4_K_M-GGUF:Q4_K_M]
# specialized in long-term goals

[nvidia/NVIDIA-Nemotron-3-Nano-4B-GGUF:Q4_K_M]
temperature = 0.8
top-p = 0.95
top-k = 20

[FermionResearch/Neutrino-8B:FV5]
temperature = 0.7
top-p = 0.9
top-k = 50

[freakyskittle/Kimi-K2.7-Code-Dflash:Q4_0]
temperature = 0.5
top-p = 0.9
top-k = 10

[DevQuasar/fdtn-ai.antares-1b-GGUF:Q4_K_M]
temperature = 0.7
top-p = 0.9
top-k = 20

[LiquidAI/LFM2.5-8B-A1B-GGUF:Q4_0]
temperature = 0.6
top-p = 0.95
top-k = 20

[bloomer010/Ling-3.0-tiny-GGUF:IQ4_XS]
temperature = 0.8
top-p = 0.9
top-k = 20
