#!/bin/bash

# requirements: 
#   anamnesis from https://github.com/oneyb/anamnesis
#   apt-get install xmonad xmobar libpango1.0-dev libpangokupfer shutter diodon
#     x11-xserver-utils trayer network-manager-gnome light-locker

if [ -x ~/.local/bin/anamnesis ] ; then
   diodon &
fi

xsetroot -solid black # feh for background image

if [ ! "$(pidof trayer)" ] ; then
   trayer --SetDockType true --SetPartialStrut true &
fi

if [ ! "$(pidof nm-applet)" ] ; then
   nm-applet --sm-disable &
fi

if [ ! "$(pidof xss-lock)" ] ; then
   light-locker-command &
fi

if [ ! "$(pidof syndaemon)" ] ; then
   syndaemon -i 2 -d -t -K &
fi

if [ ! "$(pidof pulseaudio)" ] ; then
   start-pulseaudio-x11
fi

if [ ! "$(pidof dropbox)" ] ; then
   dropbox start
fi

# sudo add-apt-repository ppa:bitseater/ppa
if [ ! "$(pidof com.gitlab.bitseater.meteo)" ] ; then
   com.gitlab.bitseater.meteo &
fi