# ghc-9.6.7, see https://www.stackage.org/lts-22.44
resolver:
  url: https://raw.githubusercontent.com/commercialhaskell/stackage-snapshots/master/lts/22/44.yaml

packages:
  - xmonad
  - xmonad-contrib
  - "."

extra-deps:
  - hostname-1.0
  - split-0.2.5
  - containers-0.6.8
  - circular-enum-0.1.0.0
  - mtl-2.3.1

# ghcup managed
system-ghc: true

notify-if-nix-on-path: false
