resolver:
  url: https://raw.githubusercontent.com/commercialhaskell/stackage-snapshots/master/lts/21/25.yaml

packages:
  - xmonad
  - xmonad-contrib
  - "."

extra-deps:
  - hostname-1.0
  - split-0.2.5

system-ghc: true

notify-if-nix-on-path: false
